apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: grade-submission
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: "YWRtaW4=" ## assumes this is base64 encoded
  MONGO_INITDB_ROOT_PASSWORD: "cGFzc3dvcmQxMjM0" ## admin:password1234
