apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb-grade-submission
  namespace: grade-submission
spec:
  members: 3
  type: ReplicaSet
  version: "6.0.5"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: user
      db: grades
      passwordSecretRef:
        name: mongodb-user-password
      roles:
        - name: readWrite
          db: grades

      scramCredentialsSecretName: mongodb-grade-submission-scram-credentials

  # statefulSet:
  #   template:
  #     spec:
  #       containers:
  #         - name: mongodb-agent
  #           volumeMounts:
  #             - name: custom-volume
  #               mountPath: /my-custom-version/mount-path
