apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: grade-submission
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: mongodb
  serviceName: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grade-submission
        app.kubernetes.io/instance: mongodb
        app.kubernetes.io/component: database
    spec:
      containers:
        - name: mongodb
          image: mongo:4.4
          envFrom:
            - secretRef:
                name: mongodb-secret

          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-persistent-storage
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongodb-persistent-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
# mongodb-persistent-storage-mongodb-0
# mongodb-persistent-storage-mongodb-1
