apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.microservice.name }}-secret
  namespace: {{ .Values.microservice.namespace}}
type: Opaque
data:
  MONGODB_USER: {{ .Values.secret.MONGODB_USER }} ## assumes this is base64 encoded
  MONGODB_PASSWORD: {{ .Values.secret.MOGODB_PASSWORD }} ## admin:password123
